package com.template.template_for_springboot.mapper;

import com.template.template_for_springboot.entity.WebMessage;
import com.template.template_for_springboot.entity.WebMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int countByExample(WebMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int deleteByExample(WebMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int insert(WebMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int insertSelective(WebMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    List<WebMessage> selectByExample(WebMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") WebMessage record, @Param("example") WebMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    int updateByExample(@Param("record") WebMessage record, @Param("example") WebMessageExample example);
}