package com.template.template_for_springboot.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WebMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public WebMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWebnameIsNull() {
            addCriterion("webName is null");
            return (Criteria) this;
        }

        public Criteria andWebnameIsNotNull() {
            addCriterion("webName is not null");
            return (Criteria) this;
        }

        public Criteria andWebnameEqualTo(String value) {
            addCriterion("webName =", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameNotEqualTo(String value) {
            addCriterion("webName <>", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameGreaterThan(String value) {
            addCriterion("webName >", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameGreaterThanOrEqualTo(String value) {
            addCriterion("webName >=", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameLessThan(String value) {
            addCriterion("webName <", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameLessThanOrEqualTo(String value) {
            addCriterion("webName <=", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameLike(String value) {
            addCriterion("webName like", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameNotLike(String value) {
            addCriterion("webName not like", value, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameIn(List<String> values) {
            addCriterion("webName in", values, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameNotIn(List<String> values) {
            addCriterion("webName not in", values, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameBetween(String value1, String value2) {
            addCriterion("webName between", value1, value2, "webname");
            return (Criteria) this;
        }

        public Criteria andWebnameNotBetween(String value1, String value2) {
            addCriterion("webName not between", value1, value2, "webname");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andType1IsNull() {
            addCriterion("type1 is null");
            return (Criteria) this;
        }

        public Criteria andType1IsNotNull() {
            addCriterion("type1 is not null");
            return (Criteria) this;
        }

        public Criteria andType1EqualTo(String value) {
            addCriterion("type1 =", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotEqualTo(String value) {
            addCriterion("type1 <>", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThan(String value) {
            addCriterion("type1 >", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThanOrEqualTo(String value) {
            addCriterion("type1 >=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThan(String value) {
            addCriterion("type1 <", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThanOrEqualTo(String value) {
            addCriterion("type1 <=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Like(String value) {
            addCriterion("type1 like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotLike(String value) {
            addCriterion("type1 not like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1In(List<String> values) {
            addCriterion("type1 in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotIn(List<String> values) {
            addCriterion("type1 not in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Between(String value1, String value2) {
            addCriterion("type1 between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotBetween(String value1, String value2) {
            addCriterion("type1 not between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andTopdomainIsNull() {
            addCriterion("topDomain is null");
            return (Criteria) this;
        }

        public Criteria andTopdomainIsNotNull() {
            addCriterion("topDomain is not null");
            return (Criteria) this;
        }

        public Criteria andTopdomainEqualTo(String value) {
            addCriterion("topDomain =", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainNotEqualTo(String value) {
            addCriterion("topDomain <>", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainGreaterThan(String value) {
            addCriterion("topDomain >", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainGreaterThanOrEqualTo(String value) {
            addCriterion("topDomain >=", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainLessThan(String value) {
            addCriterion("topDomain <", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainLessThanOrEqualTo(String value) {
            addCriterion("topDomain <=", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainLike(String value) {
            addCriterion("topDomain like", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainNotLike(String value) {
            addCriterion("topDomain not like", value, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainIn(List<String> values) {
            addCriterion("topDomain in", values, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainNotIn(List<String> values) {
            addCriterion("topDomain not in", values, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainBetween(String value1, String value2) {
            addCriterion("topDomain between", value1, value2, "topdomain");
            return (Criteria) this;
        }

        public Criteria andTopdomainNotBetween(String value1, String value2) {
            addCriterion("topDomain not between", value1, value2, "topdomain");
            return (Criteria) this;
        }

        public Criteria andSimplemaIsNull() {
            addCriterion("simpleMa is null");
            return (Criteria) this;
        }

        public Criteria andSimplemaIsNotNull() {
            addCriterion("simpleMa is not null");
            return (Criteria) this;
        }

        public Criteria andSimplemaEqualTo(String value) {
            addCriterion("simpleMa =", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaNotEqualTo(String value) {
            addCriterion("simpleMa <>", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaGreaterThan(String value) {
            addCriterion("simpleMa >", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaGreaterThanOrEqualTo(String value) {
            addCriterion("simpleMa >=", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaLessThan(String value) {
            addCriterion("simpleMa <", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaLessThanOrEqualTo(String value) {
            addCriterion("simpleMa <=", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaLike(String value) {
            addCriterion("simpleMa like", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaNotLike(String value) {
            addCriterion("simpleMa not like", value, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaIn(List<String> values) {
            addCriterion("simpleMa in", values, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaNotIn(List<String> values) {
            addCriterion("simpleMa not in", values, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaBetween(String value1, String value2) {
            addCriterion("simpleMa between", value1, value2, "simplema");
            return (Criteria) this;
        }

        public Criteria andSimplemaNotBetween(String value1, String value2) {
            addCriterion("simpleMa not between", value1, value2, "simplema");
            return (Criteria) this;
        }

        public Criteria andSiteIsNull() {
            addCriterion("site is null");
            return (Criteria) this;
        }

        public Criteria andSiteIsNotNull() {
            addCriterion("site is not null");
            return (Criteria) this;
        }

        public Criteria andSiteEqualTo(String value) {
            addCriterion("site =", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotEqualTo(String value) {
            addCriterion("site <>", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThan(String value) {
            addCriterion("site >", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThanOrEqualTo(String value) {
            addCriterion("site >=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThan(String value) {
            addCriterion("site <", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThanOrEqualTo(String value) {
            addCriterion("site <=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLike(String value) {
            addCriterion("site like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotLike(String value) {
            addCriterion("site not like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteIn(List<String> values) {
            addCriterion("site in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotIn(List<String> values) {
            addCriterion("site not in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteBetween(String value1, String value2) {
            addCriterion("site between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotBetween(String value1, String value2) {
            addCriterion("site not between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andWebtypeIsNull() {
            addCriterion("webType is null");
            return (Criteria) this;
        }

        public Criteria andWebtypeIsNotNull() {
            addCriterion("webType is not null");
            return (Criteria) this;
        }

        public Criteria andWebtypeEqualTo(String value) {
            addCriterion("webType =", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeNotEqualTo(String value) {
            addCriterion("webType <>", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeGreaterThan(String value) {
            addCriterion("webType >", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeGreaterThanOrEqualTo(String value) {
            addCriterion("webType >=", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeLessThan(String value) {
            addCriterion("webType <", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeLessThanOrEqualTo(String value) {
            addCriterion("webType <=", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeLike(String value) {
            addCriterion("webType like", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeNotLike(String value) {
            addCriterion("webType not like", value, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeIn(List<String> values) {
            addCriterion("webType in", values, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeNotIn(List<String> values) {
            addCriterion("webType not in", values, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeBetween(String value1, String value2) {
            addCriterion("webType between", value1, value2, "webtype");
            return (Criteria) this;
        }

        public Criteria andWebtypeNotBetween(String value1, String value2) {
            addCriterion("webType not between", value1, value2, "webtype");
            return (Criteria) this;
        }

        public Criteria andIcpIsNull() {
            addCriterion("ICP is null");
            return (Criteria) this;
        }

        public Criteria andIcpIsNotNull() {
            addCriterion("ICP is not null");
            return (Criteria) this;
        }

        public Criteria andIcpEqualTo(String value) {
            addCriterion("ICP =", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotEqualTo(String value) {
            addCriterion("ICP <>", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpGreaterThan(String value) {
            addCriterion("ICP >", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpGreaterThanOrEqualTo(String value) {
            addCriterion("ICP >=", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLessThan(String value) {
            addCriterion("ICP <", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLessThanOrEqualTo(String value) {
            addCriterion("ICP <=", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpLike(String value) {
            addCriterion("ICP like", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotLike(String value) {
            addCriterion("ICP not like", value, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpIn(List<String> values) {
            addCriterion("ICP in", values, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotIn(List<String> values) {
            addCriterion("ICP not in", values, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpBetween(String value1, String value2) {
            addCriterion("ICP between", value1, value2, "icp");
            return (Criteria) this;
        }

        public Criteria andIcpNotBetween(String value1, String value2) {
            addCriterion("ICP not between", value1, value2, "icp");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNull() {
            addCriterion("license is null");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNotNull() {
            addCriterion("license is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseEqualTo(String value) {
            addCriterion("license =", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotEqualTo(String value) {
            addCriterion("license <>", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThan(String value) {
            addCriterion("license >", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("license >=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThan(String value) {
            addCriterion("license <", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThanOrEqualTo(String value) {
            addCriterion("license <=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLike(String value) {
            addCriterion("license like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotLike(String value) {
            addCriterion("license not like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseIn(List<String> values) {
            addCriterion("license in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotIn(List<String> values) {
            addCriterion("license not in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseBetween(String value1, String value2) {
            addCriterion("license between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotBetween(String value1, String value2) {
            addCriterion("license not between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andManulcheckIsNull() {
            addCriterion("manulCheck is null");
            return (Criteria) this;
        }

        public Criteria andManulcheckIsNotNull() {
            addCriterion("manulCheck is not null");
            return (Criteria) this;
        }

        public Criteria andManulcheckEqualTo(String value) {
            addCriterion("manulCheck =", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckNotEqualTo(String value) {
            addCriterion("manulCheck <>", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckGreaterThan(String value) {
            addCriterion("manulCheck >", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckGreaterThanOrEqualTo(String value) {
            addCriterion("manulCheck >=", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckLessThan(String value) {
            addCriterion("manulCheck <", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckLessThanOrEqualTo(String value) {
            addCriterion("manulCheck <=", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckLike(String value) {
            addCriterion("manulCheck like", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckNotLike(String value) {
            addCriterion("manulCheck not like", value, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckIn(List<String> values) {
            addCriterion("manulCheck in", values, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckNotIn(List<String> values) {
            addCriterion("manulCheck not in", values, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckBetween(String value1, String value2) {
            addCriterion("manulCheck between", value1, value2, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andManulcheckNotBetween(String value1, String value2) {
            addCriterion("manulCheck not between", value1, value2, "manulcheck");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNull() {
            addCriterion("isValid is null");
            return (Criteria) this;
        }

        public Criteria andIsvalidIsNotNull() {
            addCriterion("isValid is not null");
            return (Criteria) this;
        }

        public Criteria andIsvalidEqualTo(String value) {
            addCriterion("isValid =", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotEqualTo(String value) {
            addCriterion("isValid <>", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThan(String value) {
            addCriterion("isValid >", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidGreaterThanOrEqualTo(String value) {
            addCriterion("isValid >=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThan(String value) {
            addCriterion("isValid <", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLessThanOrEqualTo(String value) {
            addCriterion("isValid <=", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidLike(String value) {
            addCriterion("isValid like", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotLike(String value) {
            addCriterion("isValid not like", value, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidIn(List<String> values) {
            addCriterion("isValid in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotIn(List<String> values) {
            addCriterion("isValid not in", values, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidBetween(String value1, String value2) {
            addCriterion("isValid between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andIsvalidNotBetween(String value1, String value2) {
            addCriterion("isValid not between", value1, value2, "isvalid");
            return (Criteria) this;
        }

        public Criteria andInnertimeIsNull() {
            addCriterion("innerTime is null");
            return (Criteria) this;
        }

        public Criteria andInnertimeIsNotNull() {
            addCriterion("innerTime is not null");
            return (Criteria) this;
        }

        public Criteria andInnertimeEqualTo(Date value) {
            addCriterion("innerTime =", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeNotEqualTo(Date value) {
            addCriterion("innerTime <>", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeGreaterThan(Date value) {
            addCriterion("innerTime >", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("innerTime >=", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeLessThan(Date value) {
            addCriterion("innerTime <", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeLessThanOrEqualTo(Date value) {
            addCriterion("innerTime <=", value, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeIn(List<Date> values) {
            addCriterion("innerTime in", values, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeNotIn(List<Date> values) {
            addCriterion("innerTime not in", values, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeBetween(Date value1, Date value2) {
            addCriterion("innerTime between", value1, value2, "innertime");
            return (Criteria) this;
        }

        public Criteria andInnertimeNotBetween(Date value1, Date value2) {
            addCriterion("innerTime not between", value1, value2, "innertime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tableone
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 17:45:16 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tableone
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}