package com.template.template_for_springboot.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
@Data
@AllArgsConstructor
@NoArgsConstructor
public class WebMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.webName
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String webname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.url
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.type1
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String type1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.topDomain
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String topdomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.simpleMa
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String simplema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.site
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.webType
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String webtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.ICP
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String icp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.license
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.manulCheck
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String manulcheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.isValid
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private String isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableone.innerTime
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    private Date innertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.webName
     *
     * @return the value of tableone.webName
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getWebname() {
        return webname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.webName
     *
     * @param webname the value for tableone.webName
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setWebname(String webname) {
        this.webname = webname == null ? null : webname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.url
     *
     * @return the value of tableone.url
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.url
     *
     * @param url the value for tableone.url
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.type1
     *
     * @return the value of tableone.type1
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.type1
     *
     * @param type1 the value for tableone.type1
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.topDomain
     *
     * @return the value of tableone.topDomain
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getTopdomain() {
        return topdomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.topDomain
     *
     * @param topdomain the value for tableone.topDomain
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setTopdomain(String topdomain) {
        this.topdomain = topdomain == null ? null : topdomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.simpleMa
     *
     * @return the value of tableone.simpleMa
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getSimplema() {
        return simplema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.simpleMa
     *
     * @param simplema the value for tableone.simpleMa
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setSimplema(String simplema) {
        this.simplema = simplema == null ? null : simplema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.site
     *
     * @return the value of tableone.site
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.site
     *
     * @param site the value for tableone.site
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.webType
     *
     * @return the value of tableone.webType
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getWebtype() {
        return webtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.webType
     *
     * @param webtype the value for tableone.webType
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setWebtype(String webtype) {
        this.webtype = webtype == null ? null : webtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.ICP
     *
     * @return the value of tableone.ICP
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getIcp() {
        return icp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.ICP
     *
     * @param icp the value for tableone.ICP
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setIcp(String icp) {
        this.icp = icp == null ? null : icp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.license
     *
     * @return the value of tableone.license
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.license
     *
     * @param license the value for tableone.license
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.manulCheck
     *
     * @return the value of tableone.manulCheck
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getManulcheck() {
        return manulcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.manulCheck
     *
     * @param manulcheck the value for tableone.manulCheck
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setManulcheck(String manulcheck) {
        this.manulcheck = manulcheck == null ? null : manulcheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.isValid
     *
     * @return the value of tableone.isValid
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public String getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.isValid
     *
     * @param isvalid the value for tableone.isValid
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setIsvalid(String isvalid) {
        this.isvalid = isvalid == null ? null : isvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableone.innerTime
     *
     * @return the value of tableone.innerTime
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public Date getInnertime() {
        return innertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableone.innerTime
     *
     * @param innertime the value for tableone.innerTime
     *
     * @mbggenerated Thu Mar 02 17:45:16 CST 2023
     */
    public void setInnertime(Date innertime) {
        this.innertime = innertime;
    }
}